title: "Giuseppe Giona"
description: "Official site of Giuseppe Giona – AI, Security, and Strategy Insights."
theme: jekyll-theme-hacker

markdown: kramdown

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

sass:
  style: compressed
